---
title: "NOAA event types with worst human health and economic losses across the United States"
author: "Jon Taylor"
date: "August 30, 2016"
output: pdf_document
---
#Synopsis

The goal of this script is to determine:  

1. The event types most harmful to human health across the United States
2. The event types with the greatest economic loss across the United States  
  
#Data Processing

  
First, lets load all the required packages and set the scientific notation
options for readability. 

```{R, warning=F, message=F}
library(dplyr)
library(readr)
library(knitr)
library(ggplot2)

#set scientific notation options
options( scipen = 0 )
options( digits = 3 )
```
  
    
Now let's import the data using read_csv() and then get a list of all the United States, 
along with Washington DC and Puerto Rico.

```{R, echo=TRUE, OUTPUT=FALSE, message=F, warning=F, cache=TRUE}

#load .csv.bz2 file
data <- read_csv("StormData.csv.bz2")

states  <-  unique(data$STATE)
states  <- states[1:52] #subset for States + Washington DC and Puerto Rico 
```  
  
  
We'll transform the data frame to get the event type with the most casualties for each state
  
    
```{R}
dataHarmed <- group_by(data, STATE, EVTYPE) %>%
    summarise(CASUALTIES=sum(FATALITIES+INJURIES)) %>%
        group_by(STATE) %>%
            top_n(1,CASUALTIES) %>%
                filter(STATE %in% states)
        
```    
 
Now, comes the hardest part. People didn't have great instruction on how to use the 
exponent fields, so we need to recode all the unique exponent values to common multipliers.

Then we'll multiply the base field by the exponential field for both the Property and Crop damage.

Finally we'll add the two fields together to get the total economic damage.


```{R}
#Find all the very unique ways people labeled exponents
unique(data$PROPDMGEXP)
unique(data$CROPDMGEXP)

#Convert these to multipliers of base 10. 10^X notation doesn't work because NA coercion
data$PROPDMGEXP.corr <-  plyr::mapvalues(data$PROPDMGEXP, from=unique(data$PROPDMGEXP), 
                    to=c("1000", "10000000", "1", "1000000000", "1000000", "1", "1",
                         "100000", "1000000", "1", "10000", "100", "1000", "100",
                         "10000000","100", "1", "10", "100000000"))

data$CROPDMGEXP.corr <-  plyr::mapvalues(data$CROPDMGEXP, from=unique(data$CROPDMGEXP), 
                    to=c("1", "1000000", "1000", "1000000", "1000000000", 
                         "", "", "1000", "100"))

#Now multiply the base and exponent columns to get the total
data$PROPDMG.total <- as.double(data$PROPDMG * as.numeric(data$PROPDMGEXP.corr))
data$CROPDMG.total <- as.double(data$CROPDMG * as.numeric(data$PROPDMGEXP.corr))

#And add the two together to get total damage from the storm
data$DMG.total <- data$PROPDMG.total + data$CROPDMG.total
```


Now let's transform the new data just like we did for the casualties above. 
Let's also get the top 10 events with the worst economic losses across the nation.

```{R}
dataDamaged <- group_by(data, STATE, EVTYPE) %>%
    summarise(LOSS=as.double(sum(DMG.total))) %>%
        group_by(STATE) %>%
            top_n(1,LOSS) %>%
                filter(STATE %in% states)

dataLoss<- group_by(data, EVTYPE) %>% 
    filter(STATE %in% states) %>%
        summarise(LOSS=as.double(sum(DMG.total))) %>% 
            top_n(10, LOSS)

```


#Results

  
  
Let's create tables listing the states and their worst event types for human health and economic losses, along with a barplot of the 10 most costly event types nation wide.  

```{R}
kable(dataHarmed, caption="Most harmful storm event types across
                           the United States by number of casualties.")



kable(dataDamaged, caption="Most harmful storm event types across
                           the United States by economic loss.")

barplot(dataLoss$LOSS, names.arg=dataLoss$EVTYPE, ylab="Economic Cost ($)", 
        main="Economic Losses By Event Type in the US", col="red", cex.names=0.3,
        las=3)
```
